### ISSUE TITLE
CSRF Protection

### ISSUE THREAD

**Issue by mmoustache** [SergeR/regionalpickup#24]
![untitled-1](https://user-images.githubusercontent.com/18294458/31431781-54852226-ae7d-11e7-95a1-0ebaa531961f.jpg)
После добавления пункта выдачи с порядковым номером 199 вылезает ошибка  CSRF Protection
Все обновления движка стоят, сайт работает в штатном режиме
![untitled-1](https://user-images.githubusercontent.com/18294458/31431765-4da4d8de-ae7d-11e7-97c2-b2c6727b2c2a.jpg)

**Comment by SergeR** [comment]
Не баг. `max_input_vars` решит проблему
